const productos=[
{nombre:"Combo 1",precio:300,imagen:"https://2img.net/i.imgur.com/UmNRnQ7.png",sector:"Alimentos"},
{nombre:"Combo 2",precio:300,imagen:"https://2img.net/i.imgur.com/NRo1XKq.png",sector:"Alimentos"},
{nombre:"Combo 3 ",precio:300,imagen:"https://2img.net/i.imgur.com/R5herbY.png",sector:"Alimentos"},
{nombre:"Ramen ",precio:200,imagen:"https://i.postimg.cc/SxxnQBPC/rammm.png",sector:"Alimentos"},
{nombre:"Salmón",precio:200,imagen:"https://2img.net/i.imgur.com/sisv2LZ.png",sector:"Alimentos"},
{nombre:"Perrito caliente",precio:100,imagen:"https://i.postimg.cc/d0Qz9vgc/image.png",sector:"Alimentos"},
{nombre:"Smalahove",precio:200,imagen:"https://2img.net/i.imgur.com/uYzrUIF.png",sector:"Alimentos"},
{nombre:"Rakfish",precio:200,imagen:"https://2img.net/i.imgur.com/ISmOUQh.png",sector:"Alimentos"},
{nombre:"Canasta 1",precio:300,imagen:"https://2img.net/i.imgur.com/RXXWuXG.png",sector:"Alimentos"},
{nombre:"Canasta 2",precio:300,imagen:"https://2img.net/i.imgur.com/WDmqhrP.png",sector:"Alimentos"},
{nombre:"canasta 3",precio:300,imagen:"https://2img.net/i.imgur.com/vG9v4fG.png",sector:"Alimentos"},
{nombre:"Canasta 4",precio:300,imagen:"https://2img.net/i.imgur.com/Lvey5Gk.png",sector:"Alimentos"},
{nombre:"Galletas",precio:100,imagen:"https://2img.net/i.imgur.com/Nvo5h1s.png",sector:"Alimentos"},
{nombre:"Chocolates",precio:100,imagen:"https://2img.net/i.imgur.com/0bJNzqw.png",sector:"Alimentos"},
{nombre:"Helado",precio:100,imagen:"https://2img.net/i.imgur.com/tsmpDou.png",sector:"Alimentos"},
{nombre:"Desayuno",precio:300,imagen:"https://2img.net/i.imgur.com/Rt1zStQ.png",sector:"Alimentos"},
{nombre:"Cena",precio:300,imagen:"https://2img.net/i.imgur.com/xP5ns1j.png",sector:"Alimentos"},
{nombre:"Macarons",precio:100,imagen:"https://2img.net/i.imgur.com/RqHSMyj.png",sector:"Alimentos"},
{nombre:"Brownies",precio:100,imagen:"https://i.postimg.cc/hPrs1xnb/image.png",sector:"Alimentos"},
{nombre:"Crepés",precio:100,imagen:"https://2img.net/i.imgur.com/mM6aFlf.png",sector:"Alimentos"},
{nombre:"Cheesecake",precio:100,imagen:"https://i.postimg.cc/MGsNXVn3/Cheesecake.png",sector:"Alimentos"},
{nombre:"Tabla de quesos",precio:100,imagen:"https://i.postimg.cc/SjqDgxXc/Tabla-de-quesos.png",sector:"Alimentos"},
{nombre:"Tacos",precio:200,imagen:"https://2img.net/i.imgur.com/P86PQoC.png",sector:"Alimentos"},
{nombre:"Snacks",precio:100,imagen:"https://images2.imgbox.com/19/3d/yUAvelhZ_o.png",sector:"Alimentos"},
{nombre:"Cupcake",precio:100,imagen:"https://2img.net/i.imgur.com/vW6XMhc.png",sector:"Alimentos"},
{nombre:"Fresas bañadas",precio:100,imagen:"https://i.postimg.cc/8cN9XS0j/image.png",sector:"Alimentos"},
{nombre:"Pastel de cumpleaños",precio:200,imagen:"https://2img.net/i.imgur.com/6Br4W9c.png",sector:"Alimentos"},
{nombre:"Espaguetis",precio:200,imagen:"https://2img.net/i.imgur.com/jf9MGZk.png",sector:"Alimentos"},
{nombre:"Sushi",precio:200,imagen:"https://2img.net/i.imgur.com/frJUb4y.png",sector:"Alimentos"},
{nombre:"Pan casero",precio:50,imagen:"https://i.postimg.cc/HLwWynxq/image.png",sector:"Alimentos"},
{nombre:"Fondue",precio:50,imagen:"https://i.postimg.cc/rdvj1LnY/Fondue-de-queso.png",sector:"Alimentos"},
{nombre:"Caviar",precio:300,imagen:"https://i.postimg.cc/XX0S3MjQ/caviar.png",sector:"Alimentos"},
{nombre:"Gofres",precio:50,imagen:"https://i.postimg.cc/4mBrzmzV/Gofres.png",sector:"Alimentos"},
{nombre:"Fiskesuppe",precio:100,imagen:"https://i.postimg.cc/21tMKM9k/Fiskesuppe.png",sector:"Alimentos"},


{nombre:"Zumo",precio:50,imagen:"https://2img.net/i.imgur.com/XupzqnT.png",sector:"Bebidas"},
{nombre:"Cerveza",precio:100,imagen:"https://2img.net/i.imgur.com/GRq45gk.png",sector:"Bebidas"},
{nombre:"Vino",precio:100,imagen:"https://2img.net/i.imgur.com/5qc2fMK.png",sector:"Bebidas"},
{nombre:"Smoothie",precio:50,imagen:"https://2img.net/i.imgur.com/cb0DGum.png",sector:"Bebidas"},
{nombre:"Kombucha",precio:50,imagen:"https://2img.net/i.imgur.com/1n3qlay.png",sector:"Bebidas"},
{nombre:"Gløgg",precio:100,imagen:"https://2img.net/i.imgur.com/xSsCS9d.png",sector:"Bebidas"},
{nombre:"Akevitt",precio:100,imagen:"https://images2.imgbox.com/fc/9f/Wr4uQGIx_o.png",sector:"Bebidas"},
{nombre:"Batido",precio:50,imagen:"https://2img.net/i.imgur.com/L3EDHr5.png",sector:"Bebidas"},
{nombre:"Cafe",precio:50,imagen:"https://2img.net/i.imgur.com/TisWwvp.png",sector:"Bebidas"},
{nombre:"Té ",precio:50,imagen:"https://2img.net/i.imgur.com/n3N7HWc.png",sector:"Bebidas"},
{nombre:"Chocolate caliente",precio:100,imagen:"https://2img.net/i.imgur.com/lz0ZlYx.png",sector:"Bebidas"},
{nombre:"Limonada",precio:50,imagen:"https://2img.net/i.imgur.com/GOOd3nt.png",sector:"Bebidas"},
{nombre:"Champagne",precio:100,imagen:"https://i.postimg.cc/ykGhC1NM/Champagne.png",sector:"Bebidas"},
{nombre:"Whisky",precio:100,imagen:"https://i.postimg.cc/gnxRDCKK/Whisky.png",sector:"Bebidas"},
{nombre:"Sidra",precio:100,imagen:"https://i.postimg.cc/7GLbLzs3/SIDRA.png",sector:"Bebidas"},
{nombre:"Hidromiel",precio:100,imagen:"https://i.postimg.cc/6QNQ677L/image.png",sector:"Bebidas"},
{nombre:"Ron",precio:100,imagen:"https://i.postimg.cc/pd1M9wfb/image.png",sector:"Bebidas"},
{nombre:"Sake",precio:100,imagen:"https://i.postimg.cc/tJWKM7LX/image.png",sector:"Bebidas"},
{nombre:"Cerveza artesanal premium",precio:300,imagen:"https://i.postimg.cc/N9qVgTwZ/Cerveza-artesanal-premium.png",sector:"Bebidas"},
{nombre:"Ponche",precio:50,imagen:"https://i.postimg.cc/Jt8gvbKC/ponche-de-frutas.png",sector:"Bebidas"},
{nombre:"Matcha",precio:50,imagen:"https://i.postimg.cc/R3LSxMrM/Matcha.png",sector:"Bebidas"},
{nombre:"Coco loco",precio:100,imagen:"https://i.postimg.cc/crtXspVC/Coco-loco.png",sector:"Bebidas"},
{nombre:"Piña colada",precio:100,imagen:"https://i.postimg.cc/PpqQ09WW/Pina-colada.png",sector:"Bebidas"},



{nombre:"Ticket de avión",precio:300,imagen:"https://2img.net/i.imgur.com/hCTn9aY.png",sector:"entretenimiento"},
{nombre:"Paseo en barco",precio:300,imagen:"https://2img.net/i.imgur.com/kDcfpRv.png",sector:"entretenimiento"},
{nombre:"Entrada para el cine",precio:100,imagen:"https://2img.net/i.imgur.com/Tf9XSMf.png",sector:"entretenimiento"},
{nombre:"Entrada para el parque de diversiones",precio:100,imagen:"https://i.postimg.cc/vmQdS5gh/image.png",sector:"entretenimiento"},
{nombre:"Entrada para el acuario",precio:100,imagen:"https://2img.net/i.imgur.com/qaz0jUd.png",sector:"entretenimiento"},
{nombre:"Entrada para el museo",precio:100,imagen:"https://2img.net/i.imgur.com/lS7YZC6.png",sector:"entretenimiento"},
{nombre:"Salida al karaoke",precio:100,imagen:"https://2img.net/i.imgur.com/zgZMIKj.png",sector:"entretenimiento"},
{nombre:"Día de SPA",precio:200,imagen:"https://2img.net/i.imgur.com/1xy5CfR.png",sector:"entretenimiento"},
{nombre:"Salida al arcade",precio:100,imagen:"https://2img.net/i.imgur.com/TDZmPf4.png",sector:"entretenimiento"},
{nombre:"Vale para comida",precio:100,imagen:"https://2img.net/i.imgur.com/BWoxXhn.png",sector:"entretenimiento"},
{nombre:"Día de picnic",precio:100,imagen:"https://2img.net/i.imgur.com/kbuE3ll.png",sector:"entretenimiento"},
{nombre:"Paseo en moto acuática",precio:300,imagen:"https://2img.net/i.imgur.com/arHl4fO.png",sector:"entretenimiento"},
{nombre:"Paseo en noria",precio:200,imagen:"https://2img.net/i.imgur.com/CxzITTM.png",sector:"entretenimiento"},
{nombre:"Salida al circo",precio:300,imagen:"https://2img.net/i.imgur.com/JkxX9gC.png",sector:"entretenimiento"},
{nombre:"Estadía en hotel",precio:400,imagen:"https://2img.net/i.imgur.com/WHh4uWC.png",sector:"entretenimiento"},
{nombre:"Entrada de concierto",precio:300,imagen:"https://2img.net/i.imgur.com/9IQ466X.png",sector:"entretenimiento"},
{nombre:"Salida al casino",precio:200,imagen:"https://2img.net/i.imgur.com/eR2nRGC.png",sector:"entretenimiento"},
{nombre:"Escape room",precio:200,imagen:"https://i.postimg.cc/bsvXFTGH/Escape-room.png",sector:"entretenimiento"},
{nombre:"Salida al bowling",precio:200,imagen:"https://i.postimg.cc/z3J4Vjk5/Bowling.png",sector:"entretenimiento"},
{nombre:"Salida al teatro",precio:200,imagen:"https://i.postimg.cc/Ff4DwrWF/Obra-de-teatro.png",sector:"entretenimiento"},
{nombre:"Día de excursión",precio:200,imagen:"https://i.postimg.cc/8fctWWVJ/image.png",sector:"entretenimiento"},
{nombre:"Día de sauna",precio:200,imagen:"https://i.postimg.cc/L8s7WPzD/image.png",sector:"entretenimiento"},
{nombre:"Salida al campo de tiro",precio:200,imagen:"https://i.postimg.cc/QF1SphRL/image.png",sector:"entretenimiento"},
{nombre:"Salida al paintball",precio:200,imagen:"https://i.postimg.cc/v1yhhCsD/image.png",sector:"entretenimiento"},
{nombre:"Entrada para el ballet",precio:200,imagen:"https://i.postimg.cc/06mWHQJZ/Entrada-para-el-ballet.png",sector:"entretenimiento"},
{nombre:"Avistamiento de auroras",precio:200,imagen:"https://i.postimg.cc/c6d9Xd1R/Avistamiento-de-auroras.png",sector:"entretenimiento"},


{nombre:"Aretes 1",imagen:"https://2img.net/i.imgur.com/NGCmw6s.png",precio:150,sector:"Moda"},
{nombre:"Aretes 2",imagen:"https://2img.net/i.imgur.com/i3pTGZP.png",precio:150,sector:"Moda"},
{nombre:"Brazalete",imagen:"https://i.postimg.cc/cCcb62sD/1.png",precio:150,sector:"Moda"},
{nombre:"Anillo 1",imagen:"https://2img.net/i.imgur.com/R21jotF.png",precio:150,sector:"Moda"},
{nombre:"Anillo 2",imagen:"https://2img.net/i.imgur.com/e7c2DXU.png",precio:200,sector:"Moda"},
{nombre:"Collar 1",imagen:"https://2img.net/i.imgur.com/RhqA8qc.png",precio:150,sector:"Moda"},
{nombre:"Collar 2",imagen:"https://images2.imgbox.com/d5/a6/bmXz0sI8_o.png",precio:200,sector:"Moda"},
{nombre:"Gafas",imagen:"https://2img.net/i.imgur.com/wX5pfjd.png",precio:100,sector:"Moda"},
{nombre:"Reloj de pulsera 1",imagen:"https://2img.net/i.imgur.com/ZnfcgKZ.png",precio:100,sector:"Moda"},
{nombre:"Reloj de pulsera 2",imagen:"https://2img.net/i.imgur.com/gTzP1CR.png",precio:100,sector:"Moda"},
{nombre:"Billetera",imagen:"https://2img.net/i.imgur.com/y3pJUCG.png",precio:100,sector:"Moda"},
{nombre:"Paraguas",imagen:"https://2img.net/i.imgur.com/cmU4EIj.png",precio:100,sector:"Moda"},
{nombre:"Bufanda",imagen:"https://2img.net/i.imgur.com/hbLqMAs.png",precio:200,sector:"Moda"},
{nombre:"Guantes",imagen:"https://i.postimg.cc/T1c4hFRS/6.png",precio:100,sector:"Moda"},
{nombre:"Gorro",imagen:"https://i.postimg.cc/wMkG3Z6r/7.png",precio:50,sector:"Moda"},
{nombre:"Calcetín",imagen:"https://i.postimg.cc/d1TSd2RB/calcetin.png",precio:50,sector:"Moda"},
{nombre:"Orejeras",imagen:"https://i.postimg.cc/d39xDpqp/8.png",precio:50,sector:"Moda"},
{nombre:"Traje de baño 1",imagen:"https://2img.net/i.imgur.com/BQJz987.png",precio:200,sector:"Moda"},
{nombre:"Traje de baño 2",imagen:"https://2img.net/i.imgur.com/j9XLddx.png",precio:200,sector:"Moda"},
{nombre:"Zapatos",imagen:"https://2img.net/i.imgur.com/KoMnPtV.png",precio:300,sector:"Moda"},
{nombre:"Chaqueta",imagen:"https://2img.net/i.imgur.com/4vEzRm2.png",precio:300,sector:"Moda"},
{nombre:"Bolso",imagen:"https://2img.net/i.imgur.com/Ob6GjyO.png",precio:200,sector:"Moda"},
{nombre:"Broche 1",imagen:"https://2img.net/i.imgur.com/uyljsGw.png",precio:100,sector:"Moda"},
{nombre:"Broche 2",imagen:"https://2img.net/i.imgur.com/qedr5zY.png",precio:100,sector:"Moda"},
{nombre:"Cinturón",imagen:"https://i.postimg.cc/zL7SMnHb/Cinturon.png",precio:50,sector:"Moda"},
{nombre:"Vestido",imagen:"https://i.postimg.cc/p9Lnm3ym/Vestido.png",precio:100,sector:"Moda"},
{nombre:"Corbata",imagen:"https://i.postimg.cc/Y025d7vF/image.png",precio:50,sector:"Moda"},
{nombre:"Gemelos",imagen:"https://i.postimg.cc/NFPzbHqc/image.png",precio:50,sector:"Moda"},
{nombre:"Traje",imagen:"https://i.postimg.cc/8z8JKdQr/image.png",precio:150,sector:"Moda"},
{nombre:"Bata",imagen:"https://i.postimg.cc/Z91Z6Gdk/image.png",precio:100,sector:"Moda"},
{nombre:"Pijama",imagen:"https://i.postimg.cc/kRym3DYL/image.png",precio:100,sector:"Moda"},
{nombre:"Camisón",imagen:"https://i.postimg.cc/D8BTxJXx/image.png",precio:100,sector:"Moda"},
{nombre:"Chaleco",imagen:"https://i.postimg.cc/YvCp7fHZ/image.png",precio:100,sector:"Moda"},
{nombre:"Sudadera",imagen:"https://i.postimg.cc/vgFF45JF/image.png",precio:50,sector:"Moda"},
{nombre:"Mochila escolar",imagen:"https://i.postimg.cc/4HvJfWyM/image.png",precio:50,sector:"Moda"},
{nombre:"Anillos de matrimonio",imagen:"https://2img.net/i.imgur.com/jhyWIKG.png",precio:400,sector:"Moda"},
{nombre:"Lusekofte",imagen:"https://i.postimg.cc/R6kYZtxn/lusekofte.png",precio:100,sector:"Moda"},
{nombre:"Botas de nieve",imagen:"https://i.postimg.cc/HJjv0zpk/Botasdenieve.png",precio:100,sector:"Moda"},
{nombre:"Máscara de esquí",imagen:"https://i.postimg.cc/Mf09ZrDk/Mascara-de-esqui.png",precio:50,sector:"Moda"},
{nombre:"Boina",imagen:"https://i.postimg.cc/yWdV24vm/Boina.png",precio:100,sector:"Moda"},
{nombre:"Camiseta de fútbol",imagen:"https://i.postimg.cc/JzksHS76/camfut.png",precio:100,sector:"Moda"},


{nombre:"Libros",precio:100,imagen:"https://2img.net/i.imgur.com/jTc6oLB.png",sector:"Juegos"},
{nombre:"Juego de mesa",precio:100,imagen:"https://2img.net/i.imgur.com/mkncTQ5.png",sector:"Juegos"},
{nombre:"Cartas",precio:50,imagen:"https://2img.net/i.imgur.com/fgDreux.png",sector:"Juegos"},
{nombre:"Muñeca",precio:100,imagen:"https://i.postimg.cc/x8P4qh0x/2.png",sector:"Juegos"},
{nombre:"Rompecabezas",precio:100,imagen:"https://2img.net/i.imgur.com/htgMIo0.png",sector:"Juegos"},
{nombre:"Figura de acción",precio:100,imagen:"https://2img.net/i.imgur.com/X5M6htC.png",sector:"Juegos"},
{nombre:"Cubo Rubik",precio:100,imagen:"https://2img.net/i.imgur.com/tb97oVT.png",sector:"Juegos"},
{nombre:"Dardos",precio:100,imagen:"https://2img.net/i.imgur.com/ho3f9yt.png",sector:"Juegos"},
{nombre:"Juguetes de niños",precio:100,imagen:"https://images2.imgbox.com/f2/92/CphZJghp_o.png",sector:"Juegos"},
{nombre:"Sonajero",precio:50,imagen:"https://images2.imgbox.com/17/14/wGBY97ka_o.png",sector:"Juegos"},
{nombre:"Oso de felpa",precio:100,imagen:"https://2img.net/i.imgur.com/zmvJ0uO.png",sector:"Juegos"},
{nombre:"Molinillo",precio:50,imagen:"https://2img.net/i.imgur.com/cJHj9I1.png",sector:"Juegos"},
{nombre:"Juego de ajedrez",precio:100,imagen:"https://2img.net/i.imgur.com/oWF2BPG.png",sector:"Juegos"},
{nombre:"Tamagotchi",precio:300,imagen:"https://i.postimg.cc/13DN6Sxg/tamagotchi.png",sector:"Juegos"},
{nombre:"Yo-yo",precio:50,imagen:"https://i.postimg.cc/9z5QF4QK/yoyo.png",sector:"Juegos"},
{nombre:"Spinner",precio:50,imagen:"https://i.postimg.cc/JhySFK7c/image.png",sector:"Juegos"},
{nombre:"Legos",precio:150,imagen:"https://i.postimg.cc/ydDRDZ7s/construccion.png",sector:"Juegos"},
{nombre:"Dominó",precio:50,imagen:"https://i.postimg.cc/hXSXYNL2/Domino.png",sector:"Juegos"},
{nombre:"Dados de rol",precio:50,imagen:"https://i.postimg.cc/YCPS5n7J/image.png",sector:"Juegos"},
{nombre:"Trencito de juguete",precio:50,imagen:"https://i.postimg.cc/nXRhPrcH/Trencito.png",sector:"Juegos"},
{nombre:"Marionetas de dedo",precio:50,imagen:"https://i.postimg.cc/d0mNpXPG/image.png",sector:"Juegos"},
{nombre:"Canicas",precio:50,imagen:"https://i.postimg.cc/x1L6N7dw/image.png",sector:"Juegos"},
{nombre:"Avioncito de papel",precio:50,imagen:"https://i.postimg.cc/G2gK1nM9/image.png",sector:"Juegos"},
{nombre:"Caballito de juguete",precio:50,imagen:"https://i.postimg.cc/15Dw5PG1/image.png",sector:"Juegos"},
{nombre:"Consola retro",precio:200,imagen:"https://i.postimg.cc/HkydqzGD/image.png",sector:"Juegos"},
{nombre:"Cartas coleccionables",precio:50,imagen:"https://i.postimg.cc/ftL2Tybq/cartascoleccionables.png",sector:"Juegos"},
{nombre:"Laberinto",precio:50,imagen:"https://i.postimg.cc/Y09bF4rK/image.png",sector:"Juegos"},
{nombre:"Pistola de agua",precio:50,imagen:"https://i.postimg.cc/MpRt1JSc/image.png",sector:"Juegos"},
{nombre:"Juego de trivia",precio:50,imagen:"https://i.postimg.cc/t4YYYWL1/image.png",sector:"Juegos"},
{nombre:"Set de magia",precio:150,imagen:"https://i.postimg.cc/s25fhcKQ/image.png",sector:"Juegos"},
{nombre:"Futbolín",precio:300,imagen:"https://i.postimg.cc/KKXQL2s0/futbolin.png",sector:"Juegos"},


{nombre:"Taza",precio:100,imagen:"https://2img.net/i.imgur.com/aRriRe3.png",sector:"Hogar"},
{nombre:"Vela aromática",precio:100,imagen:"https://images2.imgbox.com/ac/33/kuoaFiXb_o.png",sector:"Hogar"},
{nombre:"Botella térmica",precio:100,imagen:"https://images2.imgbox.com/41/88/05IsPivB_o.png",sector:"Hogar"},
{nombre:"Portaretratos",precio:100,imagen:"https://2img.net/i.imgur.com/gcWCdd8.png",sector:"Hogar"},
{nombre:"Planta",precio:100,imagen:"https://2img.net/i.imgur.com/tLe7fMl.png",sector:"Hogar"},
{nombre:"Ramo de flores",precio:100,imagen:"https://2img.net/i.imgur.com/1QE2Q0k.png",sector:"Hogar"},
{nombre:"Maquillaje",precio:200,imagen:"https://2img.net/i.imgur.com/Lg6FBgI.png",sector:"Hogar"},
{nombre:"Skincare",precio:300,imagen:"https://2img.net/i.imgur.com/D5UZ2rM.png",sector:"Hogar"},
{nombre:"Colonia de hombre",precio:100,imagen:"https://2img.net/i.imgur.com/44AWtV7.png",sector:"Hogar"},
{nombre:"Perfume de mujer",precio:100,imagen:"https://2img.net/i.imgur.com/zTZVAcz.png",sector:"Hogar"},
{nombre:"Navaja",precio:100,imagen:"https://2img.net/i.imgur.com/I13rh57.png",sector:"Hogar"},
{nombre:"Esmalte para uñas",precio:200,imagen:"https://2img.net/i.imgur.com/CQ6wurx.png",sector:"Hogar"},
{nombre:"Difusor de ambiente",precio:150,imagen:"https://i.postimg.cc/j5RVTLLK/image.png",sector:"Hogar"},
{nombre:"Cuenco de cerámica",precio:50,imagen:"https://i.postimg.cc/YCNxCWnK/image.png",sector:"Hogar"},
{nombre:"Cuadro",precio:100,imagen:"https://i.postimg.cc/PrCXHbqY/image.png",sector:"Hogar"},
{nombre:"Recetario",precio:100,imagen:"https://i.postimg.cc/gjnWYdGJ/image.png",sector:"Hogar"},
{nombre:"Aceites esenciales",precio:100,imagen:"https://i.postimg.cc/9QGjXLHG/image.png",sector:"Hogar"},
{nombre:"Juego de té",precio:50,imagen:"https://i.postimg.cc/kgD1smmp/image.png",sector:"Hogar"},
{nombre:"Caja fuerte",precio:200,imagen:"https://i.postimg.cc/D0HdbBpw/image.png",sector:"Hogar"},
{nombre:"Lámpara",precio:50,imagen:"https://i.postimg.cc/k5sQynhC/image.png",sector:"Hogar"},
{nombre:"Humidificador",precio:50,imagen:"https://i.postimg.cc/wvSkG9Lk/image.png",sector:"Hogar"},
{nombre:"Reloj vintage",precio:150,imagen:"https://i.postimg.cc/9FPBL5M8/image.png",sector:"Hogar"},
{nombre:"Jarrón",precio:50,imagen:"https://i.postimg.cc/T1JWJx9Y/image.png",sector:"Hogar"},
{nombre:"Tocadiscos",precio:200,imagen:"https://i.postimg.cc/Mvv5XDYq/Tocadiscos.png",sector:"Hogar"},


{nombre:"Cigarros",precio:100,imagen:"https://2img.net/i.imgur.com/zkvQ2lV.png",sector:"Objetos"},
{nombre:"Rosario",precio:100,imagen:"https://2img.net/i.imgur.com/fbW8xsk.png",sector:"Objetos"},
{nombre:"Amuleto",precio:100,imagen:"https://i.postimg.cc/D0cMmH2Y/4.png",sector:"Objetos"},
{nombre:"Cristales",precio:100,imagen:"https://i.postimg.cc/Gtj59Vc5/5.png",sector:"Objetos"},
{nombre:"Set de dibujo/pintura",precio:100,imagen:"https://2img.net/i.imgur.com/tfVqewA.png",sector:"Objetos"},
{nombre:"Caja de herramientas",precio:200,imagen:"https://2img.net/i.imgur.com/l68KuE8.png",sector:"Objetos"},
{nombre:"Guitarra eléctrica",precio:400,imagen:"https://images2.imgbox.com/cc/42/1eQisBA0_o.png",sector:"Objetos"},
{nombre:"Guitarra clásica",precio:400,imagen:"https://2img.net/i.imgur.com/z8JY7wi.png",sector:"Objetos"},
{nombre:"Cuerdas de repuesto",precio:100,imagen:"https://i.postimg.cc/gkZgMG24/image.png",sector:"Objetos"},
{nombre:"Corazón de origami",precio:50,imagen:"https://2img.net/i.imgur.com/CBFjkd0.png",sector:"Objetos"},
{nombre:"Cangrejo de origami",precio:50,imagen:"https://2img.net/i.imgur.com/YDgZYW0.png",sector:"Objetos"},
{nombre:"Bola de cristal",precio:100,imagen:"https://2img.net/i.imgur.com/Y29u1jp.png",sector:"Objetos"},
{nombre:"Funda de teléfono",precio:100,imagen:"https://2img.net/i.imgur.com/gKUKarj.png",sector:"Objetos"},
{nombre:"Esposas",precio:100,imagen:"https://2img.net/i.imgur.com/3OOoMcS.png",sector:"Objetos"},
{nombre:"Mochila",precio:150,imagen:"https://2img.net/i.imgur.com/VgvThMY.png",sector:"Objetos"},
{nombre:"Campanas de viento",precio:100,imagen:"https://2img.net/i.imgur.com/pWi1jly.png",sector:"Objetos"},
{nombre:"Discos de vinilo",precio:100,imagen:"https://2img.net/i.imgur.com/VkISvSo.png",sector:"Objetos"},
{nombre:"Diario",precio:150,imagen:"https://2img.net/i.imgur.com/9DyALff.png",sector:"Objetos"},
{nombre:"Libreta",precio:100,imagen:"https://2img.net/i.imgur.com/oB52yR3.png",sector:"Objetos"},
{nombre:"Bolígrafo",precio:100,imagen:"https://2img.net/i.imgur.com/8fZKqNu.png",sector:"Objetos"},
{nombre:"Cartas de tarot",precio:150,imagen:"https://2img.net/i.imgur.com/j6ERZoV.png",sector:"Objetos"},
{nombre:"Globos",precio:100,imagen:"https://2img.net/i.imgur.com/Ox2VlLN.png",sector:"Objetos"},
{nombre:"Atrapasueños",precio:100,imagen:"https://i.postimg.cc/BQ080yPP/atrapasuenos.png",sector:"Objetos"},
{nombre:"Brújula",precio:50,imagen:"https://i.postimg.cc/g25kGqPf/image.png",sector:"Objetos"},
{nombre:"Linterna",precio:50,imagen:"https://i.postimg.cc/Dzgjq5y9/image.png",sector:"Objetos"},
{nombre:"Notitas adhesivas",precio:150,imagen:"https://i.postimg.cc/YqZJ9XhJ/image.png",sector:"Objetos"},
{nombre:"Kit de costura",precio:150,imagen:"https://i.postimg.cc/Y0pwX10y/kit-de-costura.png",sector:"Objetos"},
{nombre:"Mechero",precio:50,imagen:"https://i.postimg.cc/7fB5pmKZ/Encendedor-mechero.png",sector:"Objetos"},
{nombre:"Llavero",precio:50,imagen:"https://i.postimg.cc/LhYQqb1s/Llavero.png",sector:"Objetos"},
{nombre:"Binoculares",precio:50,imagen:"https://i.postimg.cc/2bPwFCZz/Binoculares.png",sector:"Objetos"},
{nombre:"Pipa",precio:50,imagen:"https://i.postimg.cc/jW2QpDHh/Pipa.png",sector:"Objetos"},
{nombre:"Escopeta",precio:250,imagen:"https://i.postimg.cc/1gS4F2tT/Escopeta.png",sector:"Objetos"},
{nombre:"Botella con mensaje",precio:50,imagen:"https://i.postimg.cc/SNQfZsDK/botell.png",sector:"Objetos"},
{nombre:"Catalejo",precio:50,imagen:"https://i.postimg.cc/rytZLKkr/image.png",sector:"Objetos"},
{nombre:"Sextante",precio:50,imagen:"https://i.postimg.cc/yNbjMzpx/image.png",sector:"Objetos"},
{nombre:"Globo terráqueo",precio:100,imagen:"https://i.postimg.cc/tT09T0tb/image.png",sector:"Objetos"},


{nombre:"Auto",precio:1000,imagen:"https://i.postimg.cc/prB6y42c/3.png",sector:"Movilidad"},
{nombre:"Moto",precio:600,imagen:"https://i.postimg.cc/dty7PFVz/moto.png",sector:"Movilidad"},
{nombre:"Monopatín eléctrico",precio:400,imagen:"https://i.postimg.cc/LX8qrZJT/monopatin-electrico.png",sector:"Movilidad"},
{nombre:"Bicicleta",precio:400,imagen:"https://images2.imgbox.com/51/65/Mtszjeho_o.png",sector:"Movilidad"},
{nombre:"Moto de nieve",precio:600,imagen:"https://i.postimg.cc/t42LfKmM/image.png",sector:"Movilidad"},
{nombre:"Kayak",precio:700,imagen:"https://i.postimg.cc/qMGY6f0T/image.png",sector:"Movilidad"},


{nombre:"Masajeador",precio:400,imagen:"https://2img.net/i.imgur.com/Z4vEtYE.png",sector:"Tecnología"},
{nombre:"Lector digital",precio:400,imagen:"https://2img.net/i.imgur.com/ancgGAm.png",sector:"Tecnología"},
{nombre:"Reloj inteligente",precio:400,imagen:"https://2img.net/i.imgur.com/Bd8E1aE.png",sector:"Tecnología"},
{nombre:"Auriculares",precio:200,imagen:"https://images2.imgbox.com/02/e8/nUJKCBUc_o.png",sector:"Tecnología"},
{nombre:"Móvil",precio:400,imagen:"https://2img.net/i.imgur.com/bSJ1aS6.png",sector:"Tecnología"},
{nombre:"Tablet",precio:500,imagen:"https://2img.net/i.imgur.com/RtReo18.png",sector:"Tecnología"},
{nombre:"Laptop",precio:600,imagen:"https://2img.net/i.imgur.com/xob9lGU.png",sector:"Tecnología"},
{nombre:"Altavoz",precio:200,imagen:"https://2img.net/i.imgur.com/qINcYW7.png",sector:"Tecnología"},
{nombre:"Juego de ordenador o consola",precio:200,imagen:"https://2img.net/i.imgur.com/t2SW1S3.png",sector:"Tecnología"},
{nombre:"Televisión",precio:500,imagen:"https://2img.net/i.imgur.com/DL3viZv.png",sector:"Tecnología"},
{nombre:"Visor de realidad virtual",precio:400,imagen:"https://2img.net/i.imgur.com/WgN0ilx.png",sector:"Tecnología"},
{nombre:"Consola de videojuegos",precio:500,imagen:"https://2img.net/i.imgur.com/RlrWwn3.png",sector:"Tecnología"},
{nombre:"Proyector",precio:400,imagen:"https://2img.net/i.imgur.com/hmiSZaL.png",sector:"Tecnología"},
{nombre:"Cargador portátil",precio:400,imagen:"https://2img.net/i.imgur.com/42itpa4.png",sector:"Tecnología"},
{nombre:"Asistente de voz inteligente",precio:200,imagen:"https://2img.net/i.imgur.com/h2zPelI.png",sector:"Tecnología"},
{nombre:"Giftcard",precio:200,imagen:"https://2img.net/i.imgur.com/lh3kFo5.png",sector:"Tecnología"},
{nombre:"Cámara",precio:300,imagen:"https://images2.imgbox.com/bf/71/kNELQ3dI_o.png",sector:"Tecnología"},
{nombre:"Telescopio",precio:400,imagen:"https://2img.net/i.imgur.com/HQjW3fd.png",sector:"Tecnología"},
{nombre:"Rasuradora",precio:200,imagen:"https://2img.net/i.imgur.com/od9LtvX.png",sector:"Tecnología"},
{nombre:"Aspiradora Robot",precio:400,imagen:"https://2img.net/i.imgur.com/pz0uQxo.png",sector:"Tecnología"},
{nombre:"Ventilador",precio:300,imagen:"https://2img.net/i.imgur.com/AZY2y5e.png",sector:"Tecnología"},
{nombre:"Plancha de cabello",precio:200,imagen:"https://2img.net/i.imgur.com/Q6tC3iW.png",sector:"Tecnología"},
{nombre:"Secador de cabello",precio:200,imagen:"https://2img.net/i.imgur.com/2a27rKq.png",sector:"Tecnología"},
{nombre:"Cámara de seguridad",precio:400,imagen:"https://2img.net/i.imgur.com/c3jdoZW.png",sector:"Tecnología"},
{nombre:"Micrófono",precio:200,imagen:"https://i.postimg.cc/Rq5LrnZF/image.png",sector:"Tecnología"},
{nombre:"Cámara web",precio:200,imagen:"https://i.postimg.cc/gkSSPR7c/image.png",sector:"Tecnología"},
{nombre:"Teclado inalámbrico",precio:200,imagen:"https://i.postimg.cc/sDkWSgQg/image.png",sector:"Tecnología"},
{nombre:"Mouse",precio:100,imagen:"https://i.postimg.cc/TPRpqLRh/image.png",sector:"Tecnología"},
{nombre:"Monitor",precio:300,imagen:"https://i.postimg.cc/sxvQ8wgW/image.png",sector:"Tecnología"},
{nombre:"Gabinete",precio:150,imagen:"https://i.postimg.cc/t4yPsfkY/image.png",sector:"Tecnología"},
{nombre:"Tableta gráfica",precio:350,imagen:"https://i.postimg.cc/v1dtqdw6/Tableta-grafica.png",sector:"Tecnología"},
{nombre:"Cámara polaroid",precio:500,imagen:"https://i.postimg.cc/LqRL26br/Polaroid.png",sector:"Tecnología"},

{nombre:"Mat",precio:100,imagen:"https://2img.net/i.imgur.com/9qZeKtn.png",sector:"Deportes"},
{nombre:"Pesas",precio:100,imagen:"https://2img.net/i.imgur.com/w2S4OEM.png",sector:"Deportes"},
{nombre:"Balones",precio:200,imagen:"https://2img.net/i.imgur.com/ESiNbXx.png",sector:"Deportes"},
{nombre:"Bate",precio:100,imagen:"https://2img.net/i.imgur.com/TJhqFuR.png",sector:"Deportes"},
{nombre:"Patines",precio:100,imagen:"https://2img.net/i.imgur.com/7p0yi5L.png",sector:"Deportes"},
{nombre:"Raqueta",precio:100,imagen:"https://images2.imgbox.com/5f/16/EjGqZIsf_o.png",sector:"Deportes"},
{nombre:"Traje artes marciales",precio:300,imagen:"https://i.postimg.cc/QM28q9px/karate.png",sector:"Deportes"},
{nombre:"Bolsa deportiva",precio:100,imagen:"https://2img.net/i.imgur.com/Pl3l51R.png",sector:"Deportes"},
{nombre:"Palos de golf",precio:200,imagen:"https://2img.net/i.imgur.com/IZQ5Ypg.png",sector:"Deportes"},
{nombre:"Guantes de box",precio:100,imagen:"https://2img.net/i.imgur.com/OFwaqeJ.png",sector:"Deportes"},
{nombre:"Palos de hockey",precio:200,imagen:"https://2img.net/i.imgur.com/QAPAfn6.png",sector:"Deportes"},
{nombre:"Zapatos de ballet",precio:100,imagen:"https://2img.net/i.imgur.com/CIRbxmq.png",sector:"Deportes"},
{nombre:"Tabla de surf",precio:150,imagen:"https://2img.net/i.imgur.com/e3XquRC.png",sector:"Deportes"},
{nombre:"Caña de pesca",precio:100,imagen:"https://2img.net/i.imgur.com/Jws2Ps8.png",sector:"Deportes"},
{nombre:"Guante de béisbol",precio:100,imagen:"https://2img.net/i.imgur.com/Zv2BRRN.png",sector:"Deportes"},
{nombre:"Traje de buceo",precio:150,imagen:"https://2img.net/i.imgur.com/UqHI87S.png",sector:"Deportes"},
{nombre:"Chaleco salvavidas",precio:200,imagen:"https://images2.imgbox.com/e9/48/JNbc94Pm_o.png",sector:"Deportes"},
{nombre:"Patineta",precio:150,imagen:"https://2img.net/i.imgur.com/dl7HMXd.png",sector:"Deportes"},
{nombre:"Paleta",precio:150,imagen:"https://2img.net/i.imgur.com/JO1wlmy.png",sector:"Deportes"},
{nombre:"Gafas de natación",precio:100,imagen:"https://2img.net/i.imgur.com/GAQfcgV.png",sector:"Deportes"},
{nombre:"Cuerda para saltar",precio:50,imagen:"https://i.postimg.cc/nCxKHRK1/Cuerda-para-saltar.png",sector:"Deportes"},
{nombre:"Rodilleras",precio:50,imagen:"https://i.postimg.cc/sXR1LGLz/image.png",sector:"Deportes"},
{nombre:"Protector bucal",precio:50,imagen:"https://i.postimg.cc/MGY8WcTZ/image.png",sector:"Deportes"},
{nombre:"Saco de boxeo",precio:250,imagen:"https://i.postimg.cc/9fbs6v8w/image.png",sector:"Deportes"},
{nombre:"Esquís",precio:100,imagen:"https://i.postimg.cc/8ssW-1YZ7/Esqui.png",sector:"Deportes"},
{nombre:"Cronómetro",precio:50,imagen:"https://i.postimg.cc/phWYvYds/Cronometro.png",sector:"Deportes"},
{nombre:"Arco",precio:150,imagen:"https://i.postimg.cc/pr9wYv6q/image.png",sector:"Deportes"},
{nombre:"Tabla de snowboard",precio:100,imagen:"https://i.postimg.cc/Jz39QPpb/snowboard.png",sector:"Deportes"},


{nombre:"Premios",precio:50,imagen:"https://2img.net/i.imgur.com/3IDo4Vr.png",sector:"Mascotas"},
{nombre:"Bola de estambre",precio:100,imagen:"https://2img.net/i.imgur.com/qBAhDzY.png",sector:"Mascotas"},
{nombre:"Pelota de perro",precio:100,imagen:"https://2img.net/i.imgur.com/PgkrK1E.png",sector:"Mascotas"},
{nombre:"Juguete de gato",precio:100,imagen:"https://2img.net/i.imgur.com/v3xz4wp.png",sector:"Mascotas"},
{nombre:"Cama de mascota",precio:200,imagen:"https://2img.net/i.imgur.com/ZbBRy45.png",sector:"Mascotas"},
{nombre:"Cepillo para mascota",precio:50,imagen:"https://2img.net/i.imgur.com/nKgFLHq.png",sector:"Mascotas"},
{nombre:"Jaula para aves",precio:200,imagen:"https://2img.net/i.imgur.com/OkLR019.png",sector:"Mascotas"},
{nombre:"Correa",precio:100,imagen:"https://2img.net/i.imgur.com/MhnfI9m.png",sector:"Mascotas"},
{nombre:"Pecera",precio:100,imagen:"https://i.postimg.cc/VdzMyS1M/Pecera.png",sector:"Mascotas"},
{nombre:"Rascador",precio:50,imagen:"https://i.postimg.cc/BPpjZgsM/Rascador-gato.png",sector:"Mascotas"},
{nombre:"Collar",precio:50,imagen:"https://i.postimg.cc/yNtWqfm0/image.png",sector:"Mascotas"},
{nombre:"Juguete ratón",precio:50,imagen:"https://i.postimg.cc/DwgGLgYh/image.png",sector:"Mascotas"},
{nombre:"Conjunto de ropa",precio:100,imagen:"https://i.postimg.cc/4nrKXxKF/Conjunto-animal.png",sector:"Mascotas"},
{nombre:"Localizador",precio:150,imagen:"https://i.postimg.cc/gxpn6tH8/Localizador-GPS.png",sector:"Mascotas"},
{nombre:"Transportador",precio:50,imagen:"https://i.postimg.cc/5HNysHG8/TRansportador.png",sector:"Mascotas"},
{nombre:"Rueda hámster",precio:50,imagen:"https://i.postimg.cc/Btvcwgkx/Rueda-para-hamster.png",sector:"Mascotas"},
{nombre:"Shampoo",precio:50,imagen:"https://i.postimg.cc/6T1LsZNW/Shampoo.png",sector:"Mascotas"},
{nombre:"Dispensador de alimento",precio:250,imagen:"https://i.postimg.cc/bs7xrjrX/Dispensador-de-comida-automatico.png",sector:"Mascotas"},


{nombre:"Hombre de jengibre",precio:50,imagen:"https://2img.net/i.imgur.com/4qBQBUd.png",sector:"Navidad"},
{nombre:"Gorro navideño",precio:50,imagen:"https://2img.net/i.imgur.com/lK48ZIn.png",sector:"Navidad"},
{nombre:"Calcetín",precio:50,imagen:"https://2img.net/i.imgur.com/nbWRrOs.png",sector:"Navidad"},
{nombre:"Reno de felpa",precio:50,imagen:"https://2img.net/i.imgur.com/8oB2R0u.png",sector:"Navidad"},
{nombre:"Suéter navideño",precio:50,imagen:"https://2img.net/i.imgur.com/dx4Xrg2.png",sector:"Navidad"},
{nombre:"Bola de nieve",precio:50,imagen:"https://2img.net/i.imgur.com/lOORiB7.png",sector:"Navidad"},
{nombre:"Adorno para el árbol",precio:50,imagen:"https://images2.imgbox.com/0c/25/kUPwgeCD_o.png",sector:"Navidad"},
{nombre:"Bastón de caramelo",precio:50,imagen:"https://2img.net/i.imgur.com/qpfBefy.png",sector:"Navidad"},
{nombre:"Casa de jengibre",precio:50,imagen:"https://2img.net/i.imgur.com/2cfeji5.png",sector:"Navidad"},
{nombre:"Muñeco de nieve",precio:50,imagen:"https://images2.imgbox.com/ae/81/N7LBOmhv_o.png",sector:"Navidad"},
{nombre:"Luces ",precio:50,imagen:"https://2img.net/i.imgur.com/vbGiJjW.png",sector:"Navidad"},
{nombre:"Árbolito ",precio:50,imagen:"https://2img.net/i.imgur.com/5IUZAL7.png",sector:"Navidad"},
{nombre:"Muérdago",precio:50,imagen:"https://2img.net/i.imgur.com/GrGqsSn.png",sector:"Navidad"},
{nombre:"Regalos ",precio:500,imagen:"https://2img.net/i.imgur.com/XjRXlTZ.png",sector:"Navidad"},
{nombre:"Tarjeta navideña",precio:50,imagen:"https://2img.net/i.imgur.com/frh48Xd.png",sector:"Navidad"},
{nombre:"Corona de navidad",precio:50,imagen:"https://2img.net/i.imgur.com/4IL9rHk.png",sector:"Navidad"},
{nombre:"Cascanueces",precio:50,imagen:"https://i.postimg.cc/XqL8qb5z/image.png",sector:"Navidad"},
{nombre:"Calendario adviento",precio:500,imagen:"https://i.postimg.cc/NjSx5bKd/image.png",sector:"Navidad"},

{nombre:"Kit de jardinería",precio:150,imagen:"https://i.postimg.cc/jjTGbLFH/image.png",sector:"Primavera"},
{nombre:"Comedero para aves",precio:150,imagen:"https://i.postimg.cc/ZRRsb3Fn/image.png",sector:"Primavera"},
{nombre:"Carpa para acampar",precio:300,imagen:"https://i.postimg.cc/4yH8tg0K/image.png",sector:"Primavera"},
{nombre:"Cesta de tulipanes",precio:100,imagen:"https://i.postimg.cc/7hjgfZ6Z/image.png",sector:"Primavera"},
{nombre:"Maceta colgante",precio:100,imagen:"https://i.postimg.cc/vBNnNZWQ/image.png",sector:"Primavera"},
{nombre:"Bonsái",precio:200,imagen:"https://i.postimg.cc/wBx0K3sK/image.png",sector:"Primavera"},
{nombre:"Sombrero de paja",precio:50,imagen:"https://i.postimg.cc/Pp0qfSqD/Sombrero-paja.png",sector:"Primavera"},
{nombre:"Fertilizante",precio:50,imagen:"https://i.postimg.cc/6yrQwLxC/Fertlizante.png",sector:"Primavera"},
{nombre:"Compostador",precio:100,imagen:"https://i.postimg.cc/Ty4dQtg9/Compost.png",sector:"Primavera"},
{nombre:"Cesta de mimbre",precio:50,imagen:"https://i.postimg.cc/Ffm0bg0g/Cesta-de-mimbre.png",sector:"Primavera"},
{nombre:"Cesta de picnic completa",precio:250,imagen:"https://i.postimg.cc/QMdh92jt/cesta-pic.png",sector:"Primavera"},


{nombre:"Protector solar",precio:50,imagen:"https://i.postimg.cc/d399GV9f/image.png",sector:"Verano"},
{nombre:"Bronceador",precio:100,imagen:"https://i.postimg.cc/ydmhz82N/image.png",sector:"Verano"},
{nombre:"Conservadora portátil",precio:200,imagen:"https://i.postimg.cc/2yHZzbGQ/image.png",sector:"Verano"},
{nombre:"Bolso térmico",precio:200,imagen:"https://i.postimg.cc/dVZyY0y0/image.png",sector:"Verano"},
{nombre:"Frisbee",precio:50,imagen:"https://i.postimg.cc/VNj0JH48/image.png",sector:"Verano"},
{nombre:"Kit playero",precio:100,imagen:"https://i.postimg.cc/KvRKPYQk/image.png",sector:"Verano"},
{nombre:"Toalla",precio:50,imagen:"https://i.postimg.cc/Tp6RkL58/Toalla-playa.png",sector:"Verano"},
{nombre:"Sombrilla",precio:100,imagen:"https://i.postimg.cc/G3yryJnx/Sombrilla.png",sector:"Verano"},
{nombre:"Flotador",precio:150,imagen:"https://i.postimg.cc/x8KWF59W/Flotador.png",sector:"Verano"},
{nombre:"Caracola",precio:50,imagen:"https://i.postimg.cc/64yz4gqk/Caracola.png",sector:"Verano"},
{nombre:"Estrella de mar",precio:50,imagen:"https://i.postimg.cc/4ndW07PB/Estrella-de-mar.png",sector:"Verano"},
{nombre:"Almeja",precio:50,imagen:"https://i.postimg.cc/8s0ZgpXx/Almeja.png",sector:"Verano"},
{nombre:"Coco",precio:50,imagen:"https://i.postimg.cc/Sn0VjZ4Q/Coco.png",sector:"Verano"},
{nombre:"Piña",precio:50,imagen:"https://i.postimg.cc/1gsHrf4j/Pina.png",sector:"Verano"},


{nombre:"Manta tejida de lana",precio:300,imagen:"https://i.postimg.cc/QCVMJ6gr/image.png",sector:"Otoño"},
{nombre:"Caja de té premium",precio:400,imagen:"https://i.postimg.cc/RC8CzLQ7/image.png",sector:"Otoño"},
{nombre:"Marcapáginas artesanal",precio:100,imagen:"https://i.postimg.cc/mkFsrKND/image.png",sector:"Otoño"},
{nombre:"Chal",precio:50,imagen:"https://i.postimg.cc/SRLMN7wT/image.png",sector:"Otoño"},
{nombre:"Cono de pino decorativo",precio:50,imagen:"https://i.postimg.cc/Zq9vyhGX/image.png",sector:"Otoño"},
{nombre:"Impermeable",precio:100,imagen:"https://i.postimg.cc/FzxYQFSk/image.png",sector:"Otoño"},
{nombre:"Calcetines térmicos",precio:100,imagen:"https://i.postimg.cc/T5yb2kX2/Calcetines-termicos.png",sector:"Otoño"},

{nombre:"Máscara de terror",precio:100,imagen:"https://i.postimg.cc/B62W92qF/image.png",sector:"Halloween"},
{nombre:"Calabaza tallada",precio:50,imagen:"https://i.postimg.cc/T1xzRh1Y/image.png",sector:"Halloween"},
{nombre:"Bolsa de dulces",precio:300,imagen:"https://i.postimg.cc/4NJDqKj9/image.png",sector:"Halloween"},
{nombre:"Sombrero de bruja",precio:200,imagen:"https://i.postimg.cc/tC2Kjqjb/image.png",sector:"Halloween"},
{nombre:"Vela",precio:50,imagen:"https://i.postimg.cc/1gDwhDgc/Vela.png",sector:"Halloween"},
{nombre:"Cuervo de felpa",precio:100,imagen:"https://i.postimg.cc/ZBV94HJx/Cuervo-peluche.png",sector:"Halloween"},
{nombre:"Dientes de vampiro",precio:50,imagen:"https://i.postimg.cc/w1PxQWhh/Dientes-vampi.png",sector:"Halloween"},
{nombre:"Lentilla de color",precio:150,imagen:"https://i.postimg.cc/WhN4NqNk/Lentillas-de-color.png",sector:"Halloween"},
{nombre:"Antifaz",precio:50,imagen:"https://i.postimg.cc/MXDWFZ7q/Antifaz.png",sector:"Halloween"},
{nombre:"Disfraz precario",precio:50,imagen:"https://i.postimg.cc/LqLSBm4P/Disfraz-precario.png",sector:"Halloween"},



{nombre:"Peluche de felpa gigante",precio:400,imagen:"https://i.postimg.cc/jqJ22150/image.png",sector:"Sanvalentín"},
{nombre:"Brazalete grabado",precio:300,imagen:"https://i.postimg.cc/9fMFh8SD/image.png",sector:"Sanvalentín"},
{nombre:"Anillos grabados",precio:200,imagen:"https://i.postimg.cc/wBGxT58Z/image.png",sector:"Sanvalentín"},
{nombre:"Degustación de vinos",precio:100,imagen:"https://i.postimg.cc/9FhmMFKY/image.png",sector:"Sanvalentín"},
{nombre:"Globo en forma de corazón",precio:100,imagen:"https://i.postimg.cc/76z4HpNV/image.png",sector:"Sanvalentín"},
{nombre:"Ramo de rosas",precio:100,imagen:"https://i.postimg.cc/VLmwwZ0J/image.png",sector:"Sanvalentín"},
{nombre:"Caja de bombones",precio:100,imagen:"https://i.postimg.cc/vcp4YcwP/Caja-de-bombones.png",sector:"Sanvalentín"},
{nombre:"Carta escrita",precio:50,imagen:"https://i.postimg.cc/kXTb1vpw/image.png",sector:"Sanvalentín"},
{nombre:"Foto enmarcada",precio:50,imagen:"https://i.postimg.cc/pL9p0b8v/image.png",sector:"Sanvalentín"},
{nombre:"Colgante mitad",precio:150,imagen:"https://i.postimg.cc/4y0YB2k8/image.png",sector:"Sanvalentín"},
{nombre:"Vale para masajes",precio:100,imagen:"https://i.postimg.cc/3R4NWCDF/image.png",sector:"Sanvalentín"},
{nombre:"Desayuno en la cama",precio:100,imagen:"https://i.postimg.cc/Rh1MnPCX/image.png",sector:"Sanvalentín"},
{nombre:"Playlist personalizada",precio:50,imagen:"https://i.postimg.cc/MMqC7RrF/Playlist-personalizada.png",sector:"Sanvalentín"},
{nombre:"Candado",precio:50,imagen:"https://i.postimg.cc/KjyWLTt9/image.png",sector:"Sanvalentín"},


{nombre:"Conejo de felpa",precio:200,imagen:"https://i.postimg.cc/G2FfSrKb/image.png",sector:"Pascua"},
{nombre:"Canasta con huevos decorados",precio:50,imagen:"https://i.postimg.cc/zXXQpsRw/image.png",sector:"Pascua"},
{nombre:"Huevos de chocolate",precio:150,imagen:"https://i.postimg.cc/y8DbC0jV/image.png",sector:"Pascua"},
{nombre:"Conejito de chocolate",precio:100,imagen:"https://i.postimg.cc/ZRFg8X3W/image.png",sector:"Pascua"},
{nombre:"Set para decorar huevos",precio:100,imagen:"https://i.postimg.cc/52YR7XLx/image.png",sector:"Pascua"},
{nombre:"Pan de Pascua trenzado",precio:100,imagen:"https://i.postimg.cc/g0RkWk91/pan.png",sector:"Pascua"},
{nombre:"Orejas de conejo",precio:100,imagen:"https://i.postimg.cc/21NWmFcc/Orejas-de-conejo.png",sector:"Pascua"},

{nombre:"Kit de cerámica",precio:400,imagen:"https://i.postimg.cc/Kjc0qT4P/image.png",sector:"Kits"},
{nombre:"Kit para hornear galletas",precio:200,imagen:"https://i.postimg.cc/c1T9KF5w/image.png",sector:"Kits"},
{nombre:"Kit de escritura",precio:300,imagen:"https://i.postimg.cc/g2LNTmcB/image.png",sector:"Kits"},
{nombre:"Kit de primeros auxilios",precio:100,imagen:"https://i.postimg.cc/cJ4MNW0h/image.png",sector:"Kits"},
{nombre:"Kit de barbería",precio:300,imagen:"https://i.postimg.cc/KcLTwjtt/image.png",sector:"Kits"},
{nombre:"Kit de supervivencia",precio:200,imagen:"https://i.postimg.cc/VNZbHN8q/image.png",sector:"Kits"},
{nombre:"Kit de pesca",precio:400,imagen:"https://i.postimg.cc/255Rz7Jc/image.png",sector:"Kits"},
{nombre:"Kit de escalada",precio:300,imagen:"https://i.postimg.cc/dQCMt1Hy/image.png",sector:"Kits"},
{nombre:"Kit de journaling",precio:200,imagen:"https://i.postimg.cc/mg26M2w8/image.png",sector:"Kits"},
{nombre:"Kit de exploración",precio:200,imagen:"https://i.postimg.cc/NGk44vLd/image.png",sector:"Kits"},
{nombre:"Kit de limpieza",precio:100,imagen:"https://i.postimg.cc/XJ35GXK3/image.png",sector:"Kits"},
{nombre:"Kit de tejido",precio:100,imagen:"https://i.postimg.cc/jjYwmCFW/image.png",sector:"Kits"},
{nombre:"Kit de arquería",precio:200,imagen:"https://i.postimg.cc/zbQybJxW/Kit-de-arqueria.png",sector:"Kits"},
{nombre:"Kit de relajación",precio:200,imagen:"https://i.postimg.cc/85g4nSsc/image.png",sector:"Kits"},

{nombre:"Mini drakkar tallado",precio:100,imagen:"https://i.postimg.cc/4dPC6q2q/Drakkar.png",sector:"Souvenirs"},
{nombre:"Amuleto vikingo",precio:100,imagen:"https://i.postimg.cc/0bRHR0HM/Amuleto-vikingo.png",sector:"Souvenirs"},
{nombre:"Cuerno para beber",precio:100,imagen:"https://i.postimg.cc/kVpfjQbs/Cuerno-para-hidromiel.png",sector:"Souvenirs"},
{nombre:"Piedra del fiordo",precio:50,imagen:"https://i.postimg.cc/nM70kQcM/Piedra-del-fiordo-Piedra-del-fiordo.png",sector:"Souvenirs"},
{nombre:"Postal de Bergen",precio:50,imagen:"https://i.postimg.cc/RWb79MVQ/Postal-de-Bergen.png",sector:"Souvenirs"},
{nombre:"Fragmento de runa",precio:50,imagen:"https://i.postimg.cc/zLsTb0hx/Fragmento-de-runa.png",sector:"Souvenirs"},
{nombre:"Faro en miniatura",precio:50,imagen:"https://i.postimg.cc/hfDZttcR/Faro-en-miniatura-Faro-mini.png",sector:"Souvenirs"},
{nombre:"Miel artesanal",precio:100,imagen:"https://i.postimg.cc/yx3gGM3s/image.png",sector:"Souvenirs"},
{nombre:"Reloj de arena",precio:50,imagen:"https://i.postimg.cc/XYYGSBC9/image.png",sector:"Souvenirs"},
{nombre:"Moneda antigua",precio:50,imagen:"https://i.postimg.cc/rp7wrRTh/image.png",sector:"Souvenirs"},
{nombre:"Mapa",precio:50,imagen:"https://i.postimg.cc/MTZd1HYQ/image.png",sector:"Souvenirs"},
{nombre:"Adorno térmico",precio:50,imagen:"https://i.postimg.cc/NM4T7x0m/ea.png",sector:"Souvenirs"},
{nombre:"Imán de Bergen",precio:50,imagen:"https://i.postimg.cc/tCRHrDgv/hf.png",sector:"Souvenirs"},
{nombre:"Cuaderno de viaje",precio:50,imagen:"https://i.postimg.cc/HVPNJQM2/Cuadernoviaje.png",sector:"Souvenirs"},
{nombre:"Barco en miniatura",precio:100,imagen:"https://i.postimg.cc/hf6NCN54/barco-en-botella.png",sector:"Souvenirs"},

]
